---
server:
  port: 2001
  context-path: /
eureka:
  instance:
    hostname: eureka2001.liyingdong.com
  client:
    register-with-eureka: false #false 由于该应用为服务注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: true     #true 由于注册中心要查询到服务实例，它需要去检索服务，所以设置为true
    service-url:
      #设置与Eureka其他注册中心交互的地址，查询其他注册中心用到
      defaultZone: http://eureka2002.liyingdong.com:2002/eureka/,http://eureka2003.liyingdong.com:2003/eureka/
spring:
  profiles: eureka2001
---
server:
  port: 2002
  context-path: /
eureka:
  instance:
    hostname: eureka2002.liyingdong.com
  client:
    register-with-eureka: false #false 由于该应用为服务注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: true     #true 由于注册中心要查询到服务实例，它需要去检索服务，所以设置为true
    service-url:
      #设置与Eureka其他注册中心交互的地址，查询其他注册中心用到
      defaultZone: http://eureka2001.liyingdong.com:2001/eureka/,http://eureka2003.liyingdong.com:2003/eureka/
spring:
  profiles: eureka2002
---
server:
  port: 2003
  context-path: /
eureka:
  instance:
    hostname: eureka2003.liyingdong.com
  client:
    register-with-eureka: false #false 由于该应用为服务注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: true     #true 由于注册中心要查询到服务实例，它需要去检索服务，所以设置为true
    service-url:
      #设置与Eureka其他注册中心交互的地址，查询其他注册中心用到
      defaultZone: http://eureka2001.liyingdong.com:2001/eureka/,http://eureka2002.liyingdong.com:2002/eureka/
spring:
  profiles: eureka2003
  