---
server:
  port: 1004
  mybatis_ssm-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.32.147/mybatis_ssm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application: 
    name: microservice-student
  profiles: provider-hystrix-1004

eureka:
  instance:
    hostname: localhost
    appname: microservice-student 
    instance-id: microservice-student:1004 
    prefer-ip-address: true 
  client:
    service-url:
     
      defaultZone: http://eureka2001.liyingdong.com:2001/eureka/,http://eureka2002.liyingdong.com:2002/eureka/,http://eureka2003.liyingdong.com:2003/eureka/   

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

info:
  groupId: com.liyingdong.springcloud
  artifactId: microservice-student-provider-1004
  version: 1.0-SNAPSHOT
  userName: http://www.liyingdong.com
  phone: 123456

---
server:
  port: 1005
  mybatis_ssm-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.32.147/mybatis_ssm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: microservice-student
  profiles: provider-hystrix-1005

eureka:
  instance:
    hostname: localhost 
    appname: microservice-student 
    instance-id: microservice-student:1005 
    prefer-ip-address: true 
  client:
    service-url:
      defaultZone: http://eureka2001.liyingdong.com:2001/eureka/,http://eureka2002.liyingdong.com:2002/eureka/,http://eureka2003.liyingdong.com:2003/eureka/   

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

info:
  groupId: com.liyingdong.springcloud
  artifactId: microservice-student-provider-1005
  version: 1.0-SNAPSHOT
  userName: http://www.liyingdong.com
  phone: 123456


---
server:
  port: 1006
  mybatis_ssm-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.32.147/mybatis_ssm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application: 
    name: microservice-student
  profiles: provider-hystrix-1006

eureka:
  instance:
    hostname: localhost  
    appname: microservice-student  
    instance-id: microservice-student:1006 
    prefer-ip-address: true 
  client:
    service-url:
      
      defaultZone: http://eureka2001.liyingdong.com:2001/eureka/,http://eureka2002.liyingdong.com:2002/eureka/,http://eureka2003.liyingdong.com:2003/eureka/   

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
info:
  groupId: com.liyingdong.springcloud
  artifactId: microservice-student-provider-1006
  version: 1.0-SNAPSHOT
  userName: http://www.liyingdong.com
  phone: 123456
  
